version: "3"


services:
  nginx:
    image: staticfloat/nginx-certbot
    restart: always
    ports:
            - 80:80/tcp
              #- 443:443/tcp
    environment:
          CERTBOT_EMAIL: tolstoy.i.m@yandex.ru
    volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
              #           - "./conf.d:/etc/nginx/user.conf.d:ro"
              #           - "letsencrypt:/etc/letsencrypt"

    depends_on:
            - test_application_1
            - test_application_2
  mongo:
    image: mongo
    volumes: 
      - "/home/ivan/mongo_database/db:/data/db"
    ports:
      - 27017:27017
  
  test_application_1:
    build: app1/
    ports:
      - 9087:9087
    links:
      - mongo
    depends_on:
      - mongo

  test_application_2:
    build: app2/
    ports:
      - 9086:9086
    links:
      - mongo
    depends_on: 
      - mongo
